version: "2"
services:
  server-api:
    container_name: server-api
    command: nodemon server.js
    build: .
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:9.6.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"
